### PR TITLE
Add a typesafe constructor for PermissionHelper

### PR DESCRIPTION
**Pull request by Allsimon**
Yet another mini-PR :)
Before you had to use

```
permissionHelper.request(new String[]{Manifest.permission.GET_ACCOUNTS,Manifest.permission.ACCESS_FINE_LOCATION);
```

Now 

```
permissionHelper.request(Manifest.permission.GET_ACCOUNTS,Manifest.permission.ACCESS_FINE_LOCATION);
```

I didn't remove the unsafe constructor because you can't use mine this way `permissionHelper.request(isSingle ? SINGLE_PERMISSION : MULTI_PERMISSIONS);`

### CODE REVIEW

**Comment by k0shk0sh** [comment]
have you run test base on this implementation? please confirm.

**Comment by Allsimon** [comment]
Testing code ? Life is too short for that :wink: 
I tested manually using the sample app, I have no idea how to add unit test for these

**Comment by k0shk0sh** [comment]
i meant running test on the sample app base on your changes.

**Comment by Allsimon** [comment]
Yes I did, do you want me to add another activity with various permissions asked ?

**Comment by k0shk0sh** [comment]
its really up to you mate. i will be accepting your pull requests on weekend tho. so you have time to do whatever you like :)

**Pull request closed without merging**
